org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.toolchains.foojay.download=true
# MC 26.2 wymaga Javy 25 takze dla samego procesu Gradle (nie tylko toolchainu).
org.gradle.java.home=/opt/jdk-25

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_version=0.157.0+26.2

mod_id=bossrun
mod_name=Boss Run Hardcore
mod_version=1.3.0
maven_group=dev.kajor
archives_base_name=bossrun
